{
	"name": "Netatmo",
	"version": "1.0.12",
	"icon": "battle-net",
	"author": "Psychokiller1888",
	"maintainers": ["maxbachmann"],
	"desc": "Get readings from your netatmo hardware",
	"aliceMinVersion": "1.0.0-a5",
	"pipRequirements": [
		"lnetatmo"
	],
	"systemRequirements": [],
	"conditions": {
		"lang": [
			"en",
			"fr",
			"de"
		],
		"online": true,
		"activeManager": [
		    "TelemetryManager"
		]
	}
}
